export const LOAD_ALL_AVAILABLE_MOVIES = 'LOAD_ALL_AVAILABLE_MOVIES';
export const LOAD_ALL_MOVIES_SUCCESS = 'LOAD_ALL_MOVIES_SUCCESS';
export const LOAD_ALL_MOVIES_ERROR = 'LOAD_ALL_MOVIES_ERROR';
export const LOAD_SPECIFIC_MOVIE = 'LOAD_SPECIFIC_MOVIE';
export const LOAD_SPECIFIC_MOVIE_SUCCESS = 'LOAD_SPECIFIC_MOVIE_SUCCESS';
export const LOAD_SPECIFIC_MOVIE_ERROR = 'LOAD_SPECIFIC_MOVIE_ERROR';
